apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alarmManagementService.configmapName }}
data:
  APP_DB_HOST: {{ .Values.alarmManagementPG.fullnameOverride }}
  APP_DB_NAME: {{ .Values.alarmManagementPG.postgresqlDatabase }}
  APP_DB_PORT: {{ .Values.db.port | quote }}
  APP_PORT: {{ .Values.alarmManagementService.portNumber | quote }}
  APP_DB_USERNAME: {{ .Values.alarmManagementPG.postgresqlUsername }}
  JAVA_OPTS: -Xms128m -Xmx256m