apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pushService.name }}
  labels:
    app: {{ .Values.pushService.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.pushService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.pushService.name }}
    spec:
      serviceAccountName: app-service-account
      containers:
        - name: {{ .Values.pushService.name }}
          image: {{ .Values.pushService.image }}
          envFrom:
            - configMapRef:
                name: {{ .Values.pushService.configmapName }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.pushService.portNumberIn }}
            - containerPort: {{ .Values.pushService.portNumberOut }}
          resources:
            limits:
              cpu: {{ .Values.pushService.resources.limits.cpu }}
              memory: {{ .Values.pushService.resources.limits.memory }}
            requests:
              cpu: {{ .Values.pushService.resources.requests.cpu }}
              memory: {{ .Values.pushService.resources.requests.memory }}